import { useState } from "react";
import DashboardLayout from "@/component/layout/DashboardLayout";
import { crops } from "@/component/data/crops";
import { cropProblems, CropProblem } from "@/component/data/problems";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/component/ui/select";
import { Textarea } from "@/component/ui/textarea";
import { Button } from "@/component/ui/button";
import { Bug, Shield, Clock, Download, CheckCircle2, AlertTriangle, XCircle } from "lucide-react";

export default function CropProblemSolver() {
  const [cropId, setCropId] = useState("");
  const [problemType, setProblemType] = useState("All");
  const [description, setDescription] = useState("");
  const [results, setResults] = useState<CropProblem[]>([]);
  const [searched, setSearched] = useState(false);

  const handleSearch = () => {
    setSearched(true);

    const desc = description.trim().toLowerCase();
    const descWords = desc.split(/\s+/).filter(Boolean);

    let filtered = cropProblems;
    if (cropId) filtered = filtered.filter((p) => p.cropId === cropId);
    if (problemType && problemType !== "All") filtered = filtered.filter((p) => p.type === problemType);

    if (descWords.length > 0) {
      filtered = filtered.filter((p) => {
        const text = `${p.name} ${p.explanation} ${p.treatment} ${p.preventiveMeasures}`.toLowerCase();
        return descWords.some((w) => text.includes(w));
      });
    }

    if (filtered.length === 0 && cropId) {
      filtered = cropProblems.filter((p) => p.cropId === cropId);
    }

    if (filtered.length === 0 && problemType !== "All") {
      filtered = cropProblems.filter((p) => p.type === problemType);
    }

    if (filtered.length === 0 && descWords.length > 0) {
      filtered = cropProblems.filter((p) => {
        const text = `${p.name} ${p.explanation}`.toLowerCase();
        return descWords.some((w) => text.includes(w));
      });
    }

    if (filtered.length === 0) {
      filtered = cropProblems.slice(0, 6);
    }

    setResults(filtered);
  };

  const handleDownload = (problem: CropProblem) => {
    const crop = crops.find(c => c.id === problem.cropId);
    const text = `AgriSmart - Crop Problem Report\n${"=".repeat(40)}\nCrop: ${crop?.name || problem.cropId}\nProblem: ${problem.name}\nType: ${problem.type}\nConfidence: ${problem.confidence}\n\nExplanation:\n${problem.explanation}\n\nTreatment:\n${problem.treatment}\n\nPreventive Measures:\n${problem.preventiveMeasures}\n\nRecovery Time: ${problem.recoveryTime}\n\nGenerated by AgriSmart Platform`;
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${problem.name.replace(/\s+/g, "_")}_report.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const ConfidenceBadge = ({ c }: { c: string }) => {
    const colors = c === "High" ? "text-success bg-success/10" : c === "Medium" ? "text-warning bg-warning/10" : "text-destructive bg-destructive/10";
    const Icon = c === "High" ? CheckCircle2 : c === "Medium" ? AlertTriangle : XCircle;
    return (
      <span className={`inline-flex items-center gap-1 text-xs font-medium px-2 py-0.5 rounded-full ${colors}`}>
        <Icon className="w-3 h-3" /> {c}
      </span>
    );
  };

  return (
    <DashboardLayout>
      <div className="space-y-6 animate-fade-up">
        <div>
          <h2 className="text-xl font-bold text-foreground">Crop Problem Solver</h2>
          <p className="text-sm text-muted-foreground">Diagnose and solve crop issues instantly</p>
        </div>

        <div className="card-agri">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="text-sm font-medium text-foreground mb-1.5 block">Select Crop</label>
              <Select value={cropId} onValueChange={setCropId}>
                <SelectTrigger><SelectValue placeholder="Choose crop" /></SelectTrigger>
                <SelectContent>{crops.map(c => <SelectItem key={c.id} value={c.id}>{c.icon} {c.name}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div>
              <label className="text-sm font-medium text-foreground mb-1.5 block">Problem Type</label>
              <Select value={problemType} onValueChange={setProblemType}>
                <SelectTrigger><SelectValue placeholder="Select type" /></SelectTrigger>
                <SelectContent>
                  {["All", "Pest", "Disease", "Nutrient Deficiency", "Water Issue"].map(t => (
                    <SelectItem key={t} value={t}>{t}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex items-end">
              <Button onClick={handleSearch} className="w-full gap-2"><Bug className="w-4 h-4" /> Diagnose</Button>
            </div>
          </div>
          <div className="mt-4">
            <label className="text-sm font-medium text-foreground mb-1.5 block">Additional Description (optional)</label>
            <Textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Describe what you observe..." rows={2} />
          </div>
        </div>

        {results.length > 0 && (
          <div className="space-y-4">
            <h3 className="font-semibold text-foreground">{results.length} Problem{results.length > 1 ? "s" : ""} Found</h3>
            {results.map(p => {
              const crop = crops.find(c => c.id === p.cropId);
              return (
                <div key={p.id} className="card-agri space-y-4">
                  <div className="flex items-start justify-between">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="font-semibold text-foreground">{p.name}</h4>
                        <ConfidenceBadge c={p.confidence} />
                      </div>
                      <p className="text-xs text-muted-foreground">{crop?.icon} {crop?.name} · {p.type}</p>
                    </div>
                    <Button size="sm" variant="outline" onClick={() => handleDownload(p)} className="gap-1.5">
                      <Download className="w-3.5 h-3.5" /> Report
                    </Button>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="p-3 rounded-lg bg-accent">
                      <p className="text-xs font-semibold text-accent-foreground mb-1">🔍 Explanation</p>
                      <p className="text-sm text-muted-foreground">{p.explanation}</p>
                    </div>
                    <div className="p-3 rounded-lg bg-accent">
                      <p className="text-xs font-semibold text-accent-foreground mb-1">💊 Treatment</p>
                      <p className="text-sm text-muted-foreground">{p.treatment}</p>
                    </div>
                    <div className="p-3 rounded-lg bg-accent">
                      <p className="text-xs font-semibold text-accent-foreground mb-1">🛡️ Prevention</p>
                      <p className="text-sm text-muted-foreground">{p.preventiveMeasures}</p>
                    </div>
                    <div className="p-3 rounded-lg bg-accent flex items-center gap-3">
                      <Clock className="w-5 h-5 text-primary shrink-0" />
                      <div>
                        <p className="text-xs font-semibold text-accent-foreground">Recovery Time</p>
                        <p className="text-sm text-muted-foreground">{p.recoveryTime}</p>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {results.length === 0 && searched && (
          <div className="card-agri text-center py-8">
            <p className="text-muted-foreground">No problems found for this combination. Try different filters.</p>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}


